package mango;
public enum TokenType {
    PLUS, MINUS, SLASH, ASTERISK,
    COLON, SEMICOLON, COMMA, PERIOD,
    BANG, EQUALS, ARROW,

    LEFT_PARENTHESIS, RIGHT_PARENTHESIS,
    LEFT_SQUARE, RIGHT_SQUARE,
    LEFT_BRACKET, RIGHT_BRACKET,
    LESS, GREATER, LESS_EQUALS, GREATER_EQUALS,
    EQUALS_EQUALS, BANG_EQUALS,

    EQUALS_EQUALS_EQUALS, BANG_EQUALS_EQUALS,

    AND, OR,

    //types
    INTEGER_TYPE,
    FLOAT_TYPE,
    STRING_TYPE,

    //keywords
    NIL, TRUE, FALSE,
    VAR, IF, ELIF, ELSE,
    WHILE, FN, CLASS,
    PRINT, RETURN, BREAK,
    CONTINUE, THIS, INIT,

    //others
    IDENTIFIER, EOF
}